name: Build and Test

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test on Rust
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Build Project
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose
