name: Build and Test

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v4
      # setup rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # cache dependencies and artifacts
      - uses: Swatinem/rust-cache@v2
      # build the project
      - name: Build
        run: cargo build --verbose
      # run tests
      - name: Run Tests
        run: cargo test --verbose

  formatter:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v4
      # setup rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      # run formatter in check mode
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  linter:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v4
      # setup rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      # cache dependencies and artifacts
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
